version: '3.7'

services:
  dev-db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: code_drills
      MYSQL_USER: cd_local_user
      MYSQL_PASSWORD: '{cd_use_secure}'
    ports:
      - "3310:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "6000:8080"
